version: '3.7'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=phil
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube_net

  db:
    image: postgres:13
    container_name: sonarqube_db
    restart: always
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=phil
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarqube_net

  sonarscanner:
    image: sonarsource/sonar-scanner-cli:latest
    # restart: always
    container_name: sonarscanner
    networks:
      - sonarqube_net
    entrypoint: ["/bin/sh", "-c", "echo 'SonarScanner is ready to use'"]

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data:

networks:
  sonarqube_net:
